############################ Default configuration #########################
baseURL = "https://demo.gethugothemes.com/northendlab/"
# site title 
title = "Northendlab | Creative Blog Template"
# theme
theme = "northendlab"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en

# disable language
disableLanguages = [""] # desable language from here

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
unsafe= true

######################### Default Parameters ###########################
[params]
# logo
logo = "images/logo.svg"
# favicon
favicon = "images/favicon.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# homepage main section
mainSections = ["posts"]
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "Designed & Developed By [Gethugothemes](https://gethugothemes.com)"

# search *** true or false (if Search is disable Menu will align in Right) ***
search = true
header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "right" # Sidebar value ("left", "right" or false)

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX


######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#E8505B"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "PT Sans:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"


######################## sidebar widgets #########################
[params.widgets]
sidebar = ["about-me", "categories", "featured-post", "tags", "social", "subscription"]
# available widget : search,about-me,authors,categories,tags,recent-post,social,promotion,subscription

# preloader
[params.preloader]
enable = false
preloader = "" # use png, jpg, svg or gif format

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2

########################## Plugings ######################################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"


############################## Social Site ##########################
[[params.social]]
icon = "fab fa-facebook" # Fontawesome icon pack https://fontawesome.com/icons
link = "#facebook"
[[params.social]]
icon = "fab fa-twitter" # Fontawesome icon pack https://fontawesome.com/icons
link = "#twitter"
[[params.social]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "#github"
[[params.social]]
icon = "fab fa-linkedin" # Fontawesome icon pack https://fontawesome.com/icons
link = "#linkedin"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

####################### Banner #######################################
[Languages.en.banner]
bg_image = "images/banner-shape.png"
title = "Hi, I'm Cameron William <br> My Blogsite is About <br> <strong>Website & Development</strong>"
image = "images/banner-image.png"

[Languages.fr.banner]
bg_image = "images/banner-shape.png"
title = "Salut je suis Cameron William <br> Mon blog est sur <br> <strong>Site Web et Développement</strong>"
image = "images/banner-image.png"

######################## About Me Widget ###############################
[Languages.en.about_me]
title = "Hi, I'm George A."
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet Libero ullamcorper."

[Languages.fr.about_me]
title = "Salut je suis George A."
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet Libero ullamcorper."

[[params.social_profile]]
icon = "fab fa-facebook" # Fontawesome icon pack https://fontawesome.com/icons
link = "#facebook"
[[params.social_profile]]
icon = "fab fa-twitter" # Fontawesome icon pack https://fontawesome.com/icons
link = "#twitter"
[[params.social_profile]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "#github"
[[params.social_profile]]
icon = "fab fa-linkedin" # Fontawesome icon pack https://fontawesome.com/icons
link = "#linkedin"

######################## call to action ###############################
[params.cta]
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."

[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

############################# English - Main Menu ########################
[[Languages.en.menu.main]]
weight = 1
url = "/"
name = "Home"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Home"
  weight = 1
  url = "homepage/classic/"
  name = "Home Classic"

  [[Languages.en.menu.main]]
  parent = "Home"
  weight = 2
  url = "homepage/creative/"
  name = "Home Creative"
  
[[Languages.en.menu.main]]
weight = 3
url = "about"
name = "About"
  
[[Languages.en.menu.main]]
weight = 4
url = "contact"
name = "Contact"
  
[[Languages.en.menu.main]]
weight = 5
url = "tools"
name = "Tools"

[[Languages.en.menu.main]]
weight = 6
url = "#"
name = "Pages"
hasChildren = true
  
  [[Languages.en.menu.main]]
  parent = "Pages"
  weight = 2
  url = "tags/tech/"
  name = "Tag"
  
  [[Languages.en.menu.main]]
  parent = "Pages"
  weight = 4
  url = "categories/hugo/"
  name = "Category"
  
  [[Languages.en.menu.main]]
  parent = "Pages"
  weight = 5
  url = "elements/"
  name = "Elements"

############################# Footer Menu ########################
[[Languages.en.menu.footer]]
weight = 1
url = "about/"
name = "About"

[[Languages.en.menu.footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[Languages.en.menu.footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

############################# French - Main Menu ########################
[[Languages.fr.menu.main]]
weight = 1
url = "/"
name = "Maison"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Maison"
  weight = 1
  url = "homepage/classic/"
  name = "Accueil Classique"

  [[Languages.fr.menu.main]]
  parent = "Maison"
  weight = 2
  url = "homepage/creative/"
  name = "Accueil Créatif"
  
[[Languages.fr.menu.main]]
weight = 2
url = "about"
name = "Quelque"
  
[[Languages.fr.menu.main]]
weight = 3
url = "contact"
name = "Contacter"
  
[[Languages.fr.menu.main]]
weight = 4
url = "tools"
name = "Outils"

[[Languages.fr.menu.main]]
weight = 5
url = "#"
name = "Pages"
hasChildren = true
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  weight = 1
  url = "tags/tech/"
  name = "Mots clés"
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  weight = 2
  url = "categories/hugo/"
  name = "Catégorie"
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  weight = 3
  url = "elements/"
  name = "Éléments"

############################# Footer Menu ########################
[[Languages.fr.menu.footer]]
weight = 1
url = "about/"
name = "Quelque"

[[Languages.fr.menu.footer]]
weight = 2
url = "privacy/"
name = "Vie privée"

[[Languages.fr.menu.footer]]
weight = 3
url = "terms-conditions/"
name = "Termes et conditions"