---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/english/author
  label: Author (en)
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/french/author
  label: Author (fr)
  create: all
  match: "**/*"
  templates:
  - author
- type: heading
  label: Blog post
- type: directory
  path: exampleSite/content/english/posts
  label: All Blogs (en)
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/french/posts
  label: All Blogs (fr)
  create: all
  match: "**/*"
  templates:
  - post
- type: heading
  label: Tools
- type: directory
  path: exampleSite/content/english/tools
  label: Tools (en)
  create: all
  match: "**/*"
  templates:
  - tools
- type: directory
  path: exampleSite/content/french/tools
  label: Tools (fr)
  create: all
  match: "**/*"
  templates:
  - tools
- type: heading
  label: All pages
- type: directory
  path: exampleSite/content/english
  label: Pages (en)
  create: all
  match: "*"
- type: directory
  path: exampleSite/content/french
  label: Pages (fr)
  create: all
  match: "*"
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config.toml
  label: config
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
